"""
Django settings for facecheck project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
# import djcelery
# import celery
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'urg%^)nu)=uo3&%d*1kfhvbw3@(e_m539m)a@zgzoppjpp97(+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "suit",
    # "djcelery",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "app",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'facecheck.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["app/template"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'facecheck.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
AUTH_USER_MODEL = 'app.User'
LANGUAGE_CODE = 'ZH-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

DATETIME_FORMAT = 'Y-m-d H:i:s'
LOGIN_REDIRECT_URL = "/"
DATE_FORMAT = 'Y-m-d'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/


STATIC_ROOT = STATIC_URL = '/static/'
#
# BROKER_URL = 'redis://:@127.0.0.1:6379/0'  #
# # 未处理任务 存放地址
#
# CELERY_RESULT_BACKEND = 'redis://:@127.0.0.1:6379/1'  ## 返回值存储地址
#
# CELERY_IMPORTS = (  # 定义任务所在位置
#     "app.task",
#
# )
#
# CELERYD_CONCURRENCY = 1  # 最多执行并发数
# CELERYD_PREFETCH_MULTIPLIER = 1  ## worker 每次取得任务数量
# CELERYD_MAX_TASKS_PER_CHILD = 900  ##  每个worker执行了多少任务就会死掉，
# CELERYD_TASK_TIME_LIMIT = 60  # 单个任务的运行时间不超过此值，否则会被SIGKILL 信号杀死
# CELERY_TASK_RESULT_EXPIRES = 60 * 30  # 任务过期时间 30分钟
# CELERYD_FORCE_EXECV = True  # 非常重要,有些情况下可以防止死锁
#
# BROKER_POOL_LIMIT = 20  # 默认celery与borker的连接池连接数
# CELERY_TASK_SERIALIZER = 'pickle'  ## 任务参数格式
# CELERY_RESULT_SERIALIZER = 'pickle'  ## 返回值格式
# CELERY_TIMEZONE = 'Asia/Shanghai'  ## 时区
# CELERY_ENABLE_UTC = True  ## 启用utc时间

# djcelery.setup_loader()
