# Generated by Django 2.2.5 on 2020-05-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clss',
            field=models.CharField(default=1, max_length=32, verbose_name='班级'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='pro',
            field=models.CharField(default=1, max_length=32, verbose_name='专业'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(default='出勤', max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='feature1',
            field=models.TextField(verbose_name='人脸特征'),
        ),
        migrations.AlterField(
            model_name='user',
            name='feature2',
            field=models.TextField(verbose_name='人脸特征'),
        ),
        migrations.AlterField(
            model_name='user',
            name='feature3',
            field=models.TextField(verbose_name='人脸特征'),
        ),
    ]
