# Generated by Django 2.2.5 on 2020-05-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200505_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='method',
            field=models.CharField(default='work', max_length=12, verbose_name='签到/签退'),
        ),
    ]
